CREATE TABLE public.default_recommendations (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alcohol_type_id int4 NULL,
    alcohol_volume_id int4 NULL,
    brand_id int4 NULL,
    consumption_type_id int4 NULL,
    "name" varchar(255) NULL,
    alcohol_subtype_id int4 NULL,
    beer_flavour_id int4 NULL,
    color_palette_id int4 DEFAULT 3 NOT NULL,
    glassware_id int4 DEFAULT 1 NOT NULL,
    order_number int4 DEFAULT 1 NOT NULL,
    CONSTRAINT recommendations_pkey_1 PRIMARY KEY (id)
);
