-- Demo data for the local stack.
--
-- Runs after the backend reports healthy, because Hibernate creates the schema
-- on startup (ddl-auto=update) and there is nothing to insert into before that.
--
-- Every row belongs to the dev user seeded in deploy/local/keycloak-realm.json,
-- which is also the ADMIN_USER_LIST entry in compose.yaml. That is what makes
-- these appear as shared reference data rather than one user's private entries.
--
-- Ids are explicit so rows can reference each other. The id columns are
-- GENERATED BY DEFAULT AS IDENTITY, so that is allowed, and the sequences are
-- moved past the seeded rows at the end so the application cannot collide.
--
-- Safe to run repeatedly. Reference/design rows are refreshed where the local visual demo
-- depends on them; transactional rows remain ON CONFLICT DO NOTHING, so saved_drinks dates
-- below are frozen at whatever CURRENT_DATE was on the first run. On a
-- long-lived volume the demo history ages; `docker-compose down -v` gives
-- you fresh dates. It also means a demo row deleted through the UI comes
-- back on the next start.

BEGIN;

-- The dev user from the Keycloak realm import.
\set dev_user '423c91e4-491f-4f82-aba6-3c982857e0e4'

INSERT INTO color_palettes (id, name, field, ink_dark, ink_light) VALUES
  (1, 'green', '#2B7454', '#F4E9CE', '#FFF6E3'),
  (2, 'brown', '#2B1A13', '#EBD9B4', '#FFF3DA'),
  (3, 'cream', '#DFD1B0', '#2B1A14', '#3B241B'),
  (4, 'red',   '#BA422C', '#F9EDD4', '#FFF4DB'),
  (5, 'blue',  '#2C4B6E', '#EFE2C8', '#FFF2D8'),
  (6, 'plum',  '#6B3350', '#F2E4CE', '#FFF0DD'),
  (7, 'amber', '#C9973B', '#2B1A14', '#342016'),
  (8, 'rose',  '#D4A0A7', '#2B1A14', '#3B211C')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, field = EXCLUDED.field,
  ink_dark = EXCLUDED.ink_dark, ink_light = EXCLUDED.ink_light;

-- The four silhouettes used by the demo recommendations. Production can keep the full catalogue.
INSERT INTO glassware (id, name, g, l, f) VALUES
  (1, 'pint', 'M8 5h18l-2.2 40a3 3 0 0 1-3 2.6h-7.6a3 3 0 0 1-3-2.6Z', 'M9.5 15h15l-1.85 29.4a1.5 1.5 0 0 1-1.5 1.3h-8.3a1.5 1.5 0 0 1-1.5-1.3Z', 'M8.7 8.4h16.6l-.42 6.6H9.12Z'),
  (3, 'wine', 'M8 5c0 12 2 17.2 9 19.6 7-2.4 9-7.6 9-19.6Z M16.1 24.6h1.8v16.6h-1.8Z M9.8 43.9h14.4v3H9.8Z', 'M9.7 12.6c.75 6.5 2.7 9.9 7.3 11.7 4.6-1.8 6.55-5.2 7.3-11.7Z', NULL),
  (4, 'highball', 'M10 4h14v39a3 3 0 0 1-3 3h-8a3 3 0 0 1-3-3Z', 'M11.4 13.6h11.2v28.9a1.5 1.5 0 0 1-1.5 1.4h-8.2a1.5 1.5 0 0 1-1.5-1.4Z', NULL),
  (11, 'beerbottle', 'M 14.5 7 h 5 A 4 2 0 0 1 19 8 L 20 15 c 1 2 2 3 3 6 c 0.5 3 0.5 4 0.5 10 v 12 a 3 3 0 0 1 -3 3 H 12 a 3 3 0 0 1 -1.5 -3 V 31 c 0 -4 0 -7 0.5 -10 c 1 -3 2 -4 3 -6 L 15 8 A 4 2 0 0 1 14.5 7 L 14 7 C 14.2 6.2 14.2 6.2 15 6 H 19 C 19.8 6.2 19.8 6.2 20 7 Z M 12 29 h 10 M 12 39 h 10', 'M11 26h12v17a2 2 0 0 1-2 2h-8a2 2 0 0 1-2-2Z', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, g = EXCLUDED.g, l = EXCLUDED.l, f = EXCLUDED.f;

INSERT INTO alcohol_volumes (id, name, volume) VALUES
  (1, 'Shot',         0.04),
  (2, 'Long drink',   0.25),
  (3, 'Small glass',  0.20),
  (4, 'Large glass',  0.30),
  (5, 'Small bottle', 0.33),
  (6, 'Pint',         0.50),
  (7, 'Bottle',       0.75)
ON CONFLICT (id) DO NOTHING;

-- Beer must be id 4. The backend's BEER_ID property defaults to 4 and decides
-- which type gets brand and flavour handling.
INSERT INTO alcohol_types (id, name, user_id, volume_ids) VALUES
  (1, 'Spirits',  :'dev_user', ARRAY[1, 2]::integer[]),
  (2, 'Wine',     :'dev_user', ARRAY[3, 4, 7]::integer[]),
  (3, 'Cocktail', :'dev_user', ARRAY[2, 4]::integer[]),
  (4, 'Beer',     :'dev_user', ARRAY[3, 5, 6]::integer[])
ON CONFLICT (id) DO NOTHING;

INSERT INTO alcohol_subtypes (id, alcohol_type_id, name, user_id) VALUES
  (1, 1, 'Gin',       :'dev_user'),
  (2, 1, 'Whisky',    :'dev_user'),
  (3, 1, 'Vodka',     :'dev_user'),
  (4, 2, 'Red',       :'dev_user'),
  (5, 2, 'White',     :'dev_user'),
  (6, 2, 'Rose',      :'dev_user'),
  (7, 3, 'Negroni',   :'dev_user'),
  (8, 3, 'Margarita', :'dev_user')
ON CONFLICT (id) DO NOTHING;

INSERT INTO consumption_types (id, name) VALUES
  (1, 'Bottle'),
  (2, 'Can'),
  (3, 'Draft/Tap')
ON CONFLICT (id) DO NOTHING;

INSERT INTO brands (id, name, user_id) VALUES
  (1, 'Heineken',   :'dev_user'),
  (2, 'Guinness',   :'dev_user'),
  (3, 'Duvel',      :'dev_user'),
  (4, 'La Chouffe', :'dev_user')
ON CONFLICT (id) DO NOTHING;

INSERT INTO beer_flavours (id, brand_id, name, user_id) VALUES
  (1, 1, 'Original', :'dev_user'),
  (2, 1, '0.0',      :'dev_user'),
  (3, 2, 'Draught',  :'dev_user'),
  (4, 3, 'Blond',    :'dev_user'),
  (5, 4, 'Blonde',   :'dev_user')
ON CONFLICT (id) DO NOTHING;

-- Default recommendations. DefaultRecommendationSource serves these to every
-- user, because the owner is in ADMIN_USER_LIST.
INSERT INTO recommendations
  (id, user_id, name, alcohol_type_id, alcohol_subtype_id, alcohol_volume_id, brand_id, beer_flavour_id, consumption_type_id, end_date, color_palette_id, glassware_id) VALUES
  (1, :'dev_user', 'Heineken pint',  4, NULL, 6, 1,    1,    3,    NULL, 1,  1),
  (2, :'dev_user', 'Guinness pint',  4, NULL, 6, 2,    3,    3,    NULL, 2,  1),
  (3, :'dev_user', 'Duvel bottle',   4, NULL, 5, 3,    4,    1,    NULL, 7, 11),
  (4, :'dev_user', 'Chouffe bottle', 4, NULL, 5, 4,    5,    1,    NULL, 4, 11),
  (5, :'dev_user', 'Gin and tonic',  1, 1,    2, NULL, NULL, NULL, NULL, 1,  4),
  (6, :'dev_user', 'Glass of red',   2, 4,    4, NULL, NULL, NULL, NULL, 4,  3)
ON CONFLICT (id) DO UPDATE SET
  color_palette_id = EXCLUDED.color_palette_id,
  glassware_id = EXCLUDED.glassware_id;

-- Recent history, so the history page has content and
-- DynamicPersonalRecommendationSource has something to decay. The date column
-- is a varchar holding an ISO date, which is what the application writes.
INSERT INTO saved_drinks
  (id, user_id, date, alcohol_type_id, alcohol_subtype_id, alcohol_volume_id, brand_id, beer_flavour_id, consumption_type_id, color_palette_id, glassware_id, comments) VALUES
  (1, :'dev_user', to_char(CURRENT_DATE,      'YYYY-MM-DD'), 4, NULL, 6, 1,    1,    3,    1,  1, NULL),
  (2, :'dev_user', to_char(CURRENT_DATE,      'YYYY-MM-DD'), 4, NULL, 6, 1,    1,    3,    1,  1, NULL),
  (3, :'dev_user', to_char(CURRENT_DATE - 1,  'YYYY-MM-DD'), 4, NULL, 5, 3,    4,    1,    7, 11, 'With dinner'),
  (4, :'dev_user', to_char(CURRENT_DATE - 3,  'YYYY-MM-DD'), 1, 1,    2, NULL, NULL, NULL, 6,  4, NULL),
  (5, :'dev_user', to_char(CURRENT_DATE - 7,  'YYYY-MM-DD'), 2, 4,    4, NULL, NULL, NULL, 4,  3, NULL),
  (6, :'dev_user', to_char(CURRENT_DATE - 14, 'YYYY-MM-DD'), 4, NULL, 6, 2,    3,    3,    2,  1, NULL)
ON CONFLICT (id) DO NOTHING;

-- Hand the identity columns back to the application.
SELECT setval(pg_get_serial_sequence('alcohol_volumes',   'id'), COALESCE((SELECT MAX(id) FROM alcohol_volumes),   1));
SELECT setval(pg_get_serial_sequence('alcohol_types',     'id'), COALESCE((SELECT MAX(id) FROM alcohol_types),     1));
SELECT setval(pg_get_serial_sequence('alcohol_subtypes',  'id'), COALESCE((SELECT MAX(id) FROM alcohol_subtypes),  1));
SELECT setval(pg_get_serial_sequence('consumption_types', 'id'), COALESCE((SELECT MAX(id) FROM consumption_types), 1));
SELECT setval(pg_get_serial_sequence('brands',            'id'), COALESCE((SELECT MAX(id) FROM brands),            1));
SELECT setval(pg_get_serial_sequence('beer_flavours',     'id'), COALESCE((SELECT MAX(id) FROM beer_flavours),     1));
SELECT setval(pg_get_serial_sequence('recommendations',   'id'), COALESCE((SELECT MAX(id) FROM recommendations),   1));
SELECT setval(pg_get_serial_sequence('saved_drinks',      'id'), COALESCE((SELECT MAX(id) FROM saved_drinks),      1));
SELECT setval(pg_get_serial_sequence('color_palettes',    'id'), COALESCE((SELECT MAX(id) FROM color_palettes),    1));
SELECT setval(pg_get_serial_sequence('glassware',         'id'), COALESCE((SELECT MAX(id) FROM glassware),         1));

COMMIT;
